# Generated by Django 4.0.10 on 2023-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_wine_colour_alter_wine_grape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='alcohol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
