# Generated by Django 4.0.10 on 2023-09-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_wine_grape_wine_grape'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
